-- add-enrollment-series.sql
-- 2026-09-24. ADDITIVE ONLY — no approval-before-running needed under the
-- destructive-change rule: creates one new table, one new function and one
-- new unique index. No existing value is changed or deleted.
--
-- WHY (operator decisions 2026-09-24): student enrollment numbers are
-- generated by the app — prefix + number with no separator, e.g.
-- HFA2026-27 + 0001 -> HFA2026-270001. Each prefix is its own series with
-- its own starting number (set in Admin Setup -> FTO Settings, usually at the
-- start of the academic year, by hand). Old series are kept, so switching
-- back continues where it stopped. Issued numbers can't be edited.
--
-- BEFORE RUNNING — the unique index at the end fails if two students already
-- share an enrollment ID. Check first (read-only); it should return no rows:
--   select enrollment_id, count(*) from public.students
--   group by enrollment_id having count(*) > 1;
--
-- REVERSIBLE:
--   drop index if exists public.students_enrollment_id_key;
--   drop function if exists public.next_enrollment_id();
--   drop table if exists public.enrollment_series;
-- (would lose the series settings and counters; issued numbers stay on the
-- students.)
--
-- Safe to re-run: IF NOT EXISTS / OR REPLACE.

create table if not exists public.enrollment_series (
  prefix       text primary key,
  start_number integer not null check (start_number >= 0),
  width        integer not null check (width between 1 and 9),
  next_number  integer not null,
  is_current   boolean not null default false,
  created_at   timestamptz not null default now()
);

-- At most one current series.
create unique index if not exists enrollment_series_one_current
  on public.enrollment_series (is_current) where is_current;

-- Same as every other table: RLS on, no policies — only the server
-- (service role) reads or writes it.
alter table public.enrollment_series enable row level security;

-- Issues the next number from the current series, or NULL if none is set up.
-- The UPDATE locks the row, so two students saved at the same moment get
-- different numbers. Formatting must match lib/enrollment.ts
-- formatEnrollmentId (zero-pad to width, never truncate).
create or replace function public.next_enrollment_id()
returns text
language plpgsql
as $$
declare
  v_prefix text;
  v_width  integer;
  v_n      integer;
begin
  update public.enrollment_series
     set next_number = next_number + 1
   where is_current
  returning prefix, width, next_number - 1 into v_prefix, v_width, v_n;

  if v_prefix is null then
    return null;
  end if;

  return v_prefix || case when length(v_n::text) >= v_width then v_n::text
                          else lpad(v_n::text, v_width, '0') end;
end;
$$;

-- Only the server may call it.
revoke execute on function public.next_enrollment_id() from public, anon, authenticated;
grant execute on function public.next_enrollment_id() to service_role;

-- No two students with the same enrollment ID (replaces the planned
-- client-side duplicate check from step D).
create unique index if not exists students_enrollment_id_key
  on public.students (enrollment_id);

-- Verify (read-only):
select * from public.enrollment_series;
select enrollment_id from public.students order by enrollment_id;
