-- Aircraft Maintenance Schedule — Phase 1
--
-- Adds a template table capturing recurring maintenance items (engine TBO,
-- annual/100-hour-style inspections, etc.) per aircraft model, plus a
-- hobbs_at_completion column on maintenance_records so a completed record
-- can anchor future "due" calculations against a specific hobbs reading.
--
-- Phase 1 scope (confirmed 2026-08-26): warnings + staff-confirmed
-- maintenance-record creation only. Nothing in this migration or the
-- feature it supports blocks scheduling/bookings — that is Phase 2,
-- deliberately deferred and NOT part of this migration.
--
-- Schema follows the training_requirement_templates convention (see
-- split-training-requirement-templates.sql): bigint identity PK, a
-- COMMENT ON TABLE, and per-column comments explaining intent.

create table if not exists aircraft_maintenance_schedule_templates (
  id bigint generated by default as identity primary key,
  aircraft_model text not null,
  item_name text not null,
  interval_type text not null check (interval_type in ('HOBBS_HOURS', 'CALENDAR_MONTHS')),
  interval_value numeric not null check (interval_value > 0),
  notes text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint aircraft_maintenance_schedule_templates_model_item_unique unique (aircraft_model, item_name)
);

comment on table aircraft_maintenance_schedule_templates is
  'Recurring maintenance items (engine TBO, inspections, etc.) per aircraft model. Referenced when an aircraft''s model is set/changed to compute due/overdue status (Phase 1: warnings only, no scheduling block). One row per (model, item).';
comment on column aircraft_maintenance_schedule_templates.aircraft_model is
  'Free-text model label — matched against aircraft.model. Also doubles as the source list for the Aircraft Model dropdown (with an "Other" free-text fallback) in AircraftFormModal/AircraftSetupTab.';
comment on column aircraft_maintenance_schedule_templates.interval_type is
  'HOBBS_HOURS: due every interval_value hobbs hours since the item''s last completion/baseline. CALENDAR_MONTHS: due every interval_value months since the same.';
comment on column aircraft_maintenance_schedule_templates.interval_value is
  'Hours (if HOBBS_HOURS) or months (if CALENDAR_MONTHS) between recurrences.';
comment on column aircraft_maintenance_schedule_templates.notes is
  'Source/caveat for this figure — engine manufacturer TBO figures are global and reliable; airframe inspection cadence is FTO/CAMP-programme specific and should be confirmed against the operator''s approved maintenance programme, not assumed from this seed data.';
comment on column aircraft_maintenance_schedule_templates.is_active is
  'Soft-disable a template row without deleting it (preserves history/foreign-key-free references from any already-created maintenance_records).';

create index if not exists idx_aircraft_maintenance_schedule_templates_model
  on aircraft_maintenance_schedule_templates (aircraft_model) where is_active;

-- Lets a completed (or baseline) maintenance_records row anchor future
-- HOBBS_HOURS due-calculations to the aircraft's hobbs reading at that
-- service, independent of hobbs_time drifting afterward.
alter table maintenance_records add column if not exists hobbs_at_completion numeric;
comment on column maintenance_records.hobbs_at_completion is
  'Aircraft hobbs reading at the time this record was completed (or, for a baseline row entered when enabling schedule tracking, the hobbs reading at last known service). Nullable — most historical records predate this feature and CALENDAR_MONTHS-only items never need it.';

-- Seed data: researched 2026-08-26, engine TBO figures from manufacturer
-- published data (Lycoming/Continental/Rotax/Austro); airframe inspection
-- cadence follows conventional CAMP-style annual/100-hour patterns pending
-- confirmation against this FTO's actual approved maintenance programme —
-- see per-row notes.
insert into aircraft_maintenance_schedule_templates (aircraft_model, item_name, interval_type, interval_value, notes)
values
  ('Cessna 172', 'Engine overhaul (TBO)', 'HOBBS_HOURS', 2000, 'Lycoming O-320/O-360 series TBO per manufacturer, typically 2000 hrs depending on exact variant — confirm against this aircraft''s specific engine model/serial.'),
  ('Cessna 172', 'Annual inspection', 'CALENDAR_MONTHS', 12, 'Conventional annual inspection cadence — confirm against operator''s approved CAMP.'),
  ('Cessna 172', '100-hour inspection', 'HOBBS_HOURS', 100, 'Conventional 100-hour inspection cadence for training/rental use — confirm against operator''s approved CAMP; this is an FAA Part 91.409 convention, not a DGCA-mandated figure.'),

  ('Tecnam P2006T', 'Engine overhaul (TBO)', 'HOBBS_HOURS', 2000, 'Rotax 912 S3 TBO per manufacturer, typically 2000 hrs — confirm exact variant/serial-specific TBO.'),
  ('Tecnam P2006T', 'Annual inspection', 'CALENDAR_MONTHS', 12, 'Conventional annual inspection cadence — confirm against operator''s approved CAMP.'),
  ('Tecnam P2006T', '100-hour inspection', 'HOBBS_HOURS', 100, 'Conventional 100-hour inspection cadence — confirm against operator''s approved CAMP.'),

  ('Piper PA-34 Seneca', 'Engine overhaul (TBO)', 'HOBBS_HOURS', 1800, 'Continental TSIO-360 series TBO per manufacturer, typically 1800 hrs depending on exact variant — confirm against this aircraft''s specific engine model/serial.'),
  ('Piper PA-34 Seneca', 'Annual inspection', 'CALENDAR_MONTHS', 12, 'Conventional annual inspection cadence — confirm against operator''s approved CAMP.'),
  ('Piper PA-34 Seneca', '100-hour inspection', 'HOBBS_HOURS', 100, 'Conventional 100-hour inspection cadence — confirm against operator''s approved CAMP.'),

  ('Diamond DA42 / DA42 NG', 'Engine overhaul (TBO)', 'HOBBS_HOURS', 1800, 'Austro AE300 (DA42 NG) TBO per manufacturer, typically 1800 hrs; earlier DA42 variants with Thielert/Continental CD-135/155 engines have different published TBOs — confirm exact engine fit before relying on this figure.'),
  ('Diamond DA42 / DA42 NG', 'Annual inspection', 'CALENDAR_MONTHS', 12, 'Conventional annual inspection cadence — confirm against operator''s approved CAMP.'),
  ('Diamond DA42 / DA42 NG', '100-hour inspection', 'HOBBS_HOURS', 100, 'Conventional 100-hour inspection cadence — confirm against operator''s approved CAMP.'),

  ('Piper PA-44 Seminole', 'Engine overhaul (TBO)', 'HOBBS_HOURS', 2000, 'Lycoming O-360 series TBO per manufacturer, typically 2000 hrs depending on exact variant — confirm against this aircraft''s specific engine model/serial.'),
  ('Piper PA-44 Seminole', 'Annual inspection', 'CALENDAR_MONTHS', 12, 'Conventional annual inspection cadence — confirm against operator''s approved CAMP.'),
  ('Piper PA-44 Seminole', '100-hour inspection', 'HOBBS_HOURS', 100, 'Conventional 100-hour inspection cadence — confirm against operator''s approved CAMP.')
on conflict do nothing;
