-- split-training-requirement-templates.sql
-- ============================================================
-- Splits training_requirements — which stored BOTH the admin-configured
-- template list (student_id IS NULL, one row per requirement per program,
-- edited in Admin Setup -> Requirements) AND every student's individual
-- assigned copy (student_id set, tracked with is_completed/completed_date/
-- completed_by) in a single table — into two tables:
--
--   training_requirement_templates  — the master list only. One row per
--     requirement per program. Never has a student_id or completion state.
--
--   training_requirements  — per-student assignments only, from now on.
--     student_id becomes NOT NULL (a row here is always a real assignment,
--     never a template). Gains a new template_id column linking back to
--     the template it was provisioned from — previously there was no such
--     link at all; lib/requirements-provisioning.ts matched by
--     program_code + requirement_name as a substitute (see its own
--     comments). That matching is reused here, one time, to backfill
--     template_id for whatever rows already exist.
--
-- WHY: sharing one table meant every query had to remember to filter by
-- student_id correctly, and one didn't — app/dashboard/instructor/page.tsx
-- calls loadTrainingRequirements() with no student filter at all, which
-- silently pulled the entire table (every template AND every student's
-- requirement rows/completion audit trail school-wide) into that page.
-- With student_id NOT NULL and templates moved to their own table, that
-- class of bug becomes structurally impossible for this table going
-- forward (the instructor dashboard's over-fetch itself is a separate,
-- follow-up fix — this migration only changes the schema).
--
-- HOW TO RUN:
-- Open your Supabase project -> SQL Editor -> paste this whole file -> Run.
-- Written to be safe to run once against a database that still has the
-- old shared-table shape. Back this up first if you have any real student
-- data by the time you run this (safe with the current dummy-student-only
-- data either way).
-- ============================================================

-- 1. Create the new templates table. id type matches training_programs'
--    own bigint-identity convention; verify against your schema (Table
--    Editor -> training_programs -> id column) if this errors.
CREATE TABLE IF NOT EXISTS training_requirement_templates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_code text NOT NULL,
  requirement_name text NOT NULL,
  requirement_category text,
  sort_order integer NOT NULL DEFAULT 99,
  validity_years numeric,
  required_before_hours integer,
  blocks_solo boolean NOT NULL DEFAULT false,
  blocks_all_flights boolean NOT NULL DEFAULT false,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE training_requirement_templates IS
  'Master requirement list per training program, managed in Admin Setup -> Requirements. Provisioned out to individual students (training_requirements) via "Sync to Students" / student creation — see lib/requirements-provisioning.ts. Editing a template here does NOT retroactively change requirements already assigned to students (intentional, preserves each student''s audit trail as of when they were provisioned).';

-- 2. Copy every existing template row (student_id IS NULL) across.
INSERT INTO training_requirement_templates
  (program_code, requirement_name, requirement_category, sort_order,
   validity_years, required_before_hours, blocks_solo, blocks_all_flights, notes)
SELECT program_code, requirement_name, requirement_category, sort_order,
       validity_years, required_before_hours, blocks_solo, blocks_all_flights, notes
FROM training_requirements
WHERE student_id IS NULL;

-- 3. Add the new link from a per-student requirement back to the template
--    it came from. Nullable: a row could in principle be added directly to
--    a student with no template (lib/store.ts's addRequirement action
--    supports this, though nothing in the UI currently calls it).
-- ON DELETE SET NULL, not the Postgres default (which would block/error
-- on deleting a template that's already been provisioned to students) —
-- RequirementsTab.tsx's delete confirmation already promises "This will
-- not affect existing student requirements," so deleting a template must
-- stay non-destructive to per-student rows; it just loses the back-link.
ALTER TABLE training_requirements ADD COLUMN IF NOT EXISTS template_id bigint
  REFERENCES training_requirement_templates(id) ON DELETE SET NULL;

COMMENT ON COLUMN training_requirements.template_id IS
  'Which training_requirement_templates row this was provisioned from, if any. NULL for rows added directly to a student with no template. Best-effort backfilled by program_code + requirement_name match for rows that existed before this column did.';

-- 4. Backfill template_id for existing per-student rows using the same
--    program_code + case-insensitive requirement_name match
--    lib/requirements-provisioning.ts already relies on elsewhere.
UPDATE training_requirements tr
SET template_id = t.id
FROM training_requirement_templates t
WHERE tr.student_id IS NOT NULL
  AND tr.template_id IS NULL
  AND t.program_code = tr.program_code
  AND lower(t.requirement_name) = lower(tr.requirement_name);

-- 5. Remove the template rows from training_requirements — they've been
--    copied to training_requirement_templates in step 2 and nothing
--    should read them from here anymore once the app code is updated.
DELETE FROM training_requirements WHERE student_id IS NULL;

-- 6. Enforce it at the schema level: every remaining/future row must be a
--    real per-student assignment. This is what makes the old "forgot to
--    filter by student_id" bug class impossible going forward — there's
--    no template row left in this table to accidentally include.
ALTER TABLE training_requirements ALTER COLUMN student_id SET NOT NULL;
