// lib/pdf.ts
// PDF generation service for student logbooks and daily operations sheets
// Uses jsPDF for PDF creation and jsPDF-AutoTable for tables

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { FlightRecord, Aircraft, StudentRecord, ScheduledFlight } from '@/types';

/**
 * Generate a student logbook PDF with all flight records
 * Includes student info, flight history table, totals, and instructor sign-off
 * 
 * @param student - The student's details
 * @param flights - Array of flight records for this student
 */
export function generateStudentLogbook(student: StudentRecord, flights: FlightRecord[]): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // ============================================================
  // HEADER
  // ============================================================
  doc.setFillColor(30, 41, 59); // Dark navy background
  doc.rect(0, 0, pageWidth, 35, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('FlightPro Manager - Student Logbook', 14, 15);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated: ${new Date().toLocaleDateString('en-IN')}`, 14, 25);
  
  // ============================================================
  // STUDENT INFORMATION
  // ============================================================
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Student Information', 14, 45);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const studentInfo = [
    `Name: ${student.name}`,
    `Enrollment ID: ${student.enrollmentId}`,
    `Training Stage: ${student.trainingStage}`,
    `Total Hours: ${student.totalHours}h`,
    `Medical Expiry: ${student.medicalExpiry || 'N/A'}`,
  ];
  studentInfo.forEach((line, i) => {
    doc.text(line, 14, 55 + i * 7);
  });
  
  // ============================================================
  // FLIGHT RECORDS TABLE
  // ============================================================
  const tableData = flights.map(f => [
    new Date(f.flightDate).toLocaleDateString('en-IN'),
    f.aircraftReg || 'N/A',
    `${f.departureTime?.slice(0, 5) || '--'} - ${f.arrivalTime?.slice(0, 5) || '--'}`,
    f.totalHours?.toFixed(1) || '0',
    f.landings?.toString() || '0',
    f.flightType || 'N/A',
    f.sortieType?.replace(/_/g, ' ') || 'N/A',
    f.instructorName || 'N/A',
    '⭐'.repeat(f.studentPerformance || 0),
  ]);
  
  autoTable(doc, {
    startY: 95,
    head: [['Date', 'Aircraft', 'Time', 'Hrs', 'Ldgs', 'Type', 'Sortie', 'Instructor', 'Perf']],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: [30, 41, 59],
      textColor: [255, 255, 255],
      fontSize: 8,
      fontStyle: 'bold',
    },
    bodyStyles: {
      fontSize: 8,
      textColor: [0, 0, 0],
    },
    alternateRowStyles: {
      fillColor: [241, 245, 249],
    },
    margin: { left: 14, right: 14 },
  });
  
  // ============================================================
  // SUMMARY
  // ============================================================
  const totalHours = flights.reduce((sum, f) => sum + (f.totalHours || 0), 0);
  const totalLandings = flights.reduce((sum, f) => sum + (f.landings || 0), 0);
  const soloHours = flights.filter(f => f.flightType === 'SOLO').reduce((sum, f) => sum + (f.totalHours || 0), 0);
  const dualHours = flights.filter(f => f.flightType === 'DUAL').reduce((sum, f) => sum + (f.totalHours || 0), 0);
  
  const finalY = (doc as any).lastAutoTable?.finalY || 150;
  
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Flight Summary', 14, finalY + 15);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const summary = [
    `Total Flights: ${flights.length}`,
    `Total Hours: ${totalHours.toFixed(1)}h`,
    `Total Landings: ${totalLandings}`,
    `Solo Hours: ${soloHours.toFixed(1)}h`,
    `Dual Hours: ${dualHours.toFixed(1)}h`,
  ];
  summary.forEach((line, i) => {
    doc.text(line, 14, finalY + 25 + i * 7);
  });
  
  // ============================================================
  // SIGN-OFF SECTION
  // ============================================================
  const signY = finalY + 70;
  doc.line(14, signY, 80, signY);
  doc.line(120, signY, 190, signY);
  doc.setFontSize(9);
  doc.text('Student Signature', 14, signY + 7);
  doc.text('Chief Flight Instructor', 120, signY + 7);
  
  // ============================================================
  // FOOTER
  // ============================================================
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text(`Generated by FlightPro Manager | ${new Date().toLocaleString('en-IN')}`, 14, 285);
  
  // Save the PDF
  doc.save(`${student.name.replace(/\s+/g, '_')}_Logbook.pdf`);
}

/**
 * Generate a daily operations sheet with all scheduled flights
 * 
 * @param date - The date for the ops sheet
 * @param flights - Array of scheduled flights for the day
 * @param aircraft - Fleet data for fuel status
 * @param weatherMetar - Current METAR string
 */
export function generateDailyOpsSheet(
  date: string,
  flights: ScheduledFlight[],
  aircraft: Aircraft[],
  weatherMetar: string = ''
): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // ============================================================
  // HEADER
  // ============================================================
  doc.setFillColor(30, 41, 59);
  doc.rect(0, 0, pageWidth, 30, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('FlightPro Manager - Daily Operations Sheet', 14, 15);
  
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`Date: ${new Date(date).toLocaleDateString('en-IN', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })}`, 14, 25);
  
  // ============================================================
  // WEATHER
  // ============================================================
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Weather Briefing', 14, 42);
  
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  if (weatherMetar) {
    doc.text(`METAR: ${weatherMetar}`, 14, 50);
  }
  
  // ============================================================
  // FLIGHT SCHEDULE TABLE
  // ============================================================
  const tableData = flights.map(f => [
    f.aircraftReg || 'N/A',
    new Date(f.startTime).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit', timeZone: 'Asia/Kolkata' }),
    new Date(f.endTime).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit', timeZone: 'Asia/Kolkata' }),
    f.studentName || 'N/A',
    f.instructorName || 'N/A',
    f.sortieType?.replace(/_/g, ' ') || 'N/A',
    f.status || 'N/A',
  ]);
  
  autoTable(doc, {
    startY: 58,
    head: [['Aircraft', 'Start', 'End', 'Student', 'Instructor', 'Sortie', 'Status']],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: [30, 41, 59],
      textColor: [255, 255, 255],
      fontSize: 8,
      fontStyle: 'bold',
    },
    bodyStyles: {
      fontSize: 8,
      textColor: [0, 0, 0],
    },
    alternateRowStyles: {
      fillColor: [241, 245, 249],
    },
    margin: { left: 14, right: 14 },
  });
  
  // ============================================================
  // FLEET FUEL STATUS
  // ============================================================
  const finalY = (doc as any).lastAutoTable?.finalY || 100;
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Fleet Fuel Status', 14, finalY + 15);
  
  const fuelData = aircraft.map(a => [
    a.registration,
    a.type,
    `${a.currentFuel}L / ${a.fuelCapacity}L`,
    `${Math.round((a.currentFuel / a.fuelCapacity) * 100)}%`,
  ]);
  
  autoTable(doc, {
    startY: finalY + 20,
    head: [['Aircraft', 'Type', 'Fuel Level', 'Percentage']],
    body: fuelData,
    theme: 'grid',
    headStyles: {
      fillColor: [30, 41, 59],
      textColor: [255, 255, 255],
      fontSize: 8,
      fontStyle: 'bold',
    },
    bodyStyles: {
      fontSize: 8,
      textColor: [0, 0, 0],
    },
    margin: { left: 14, right: 14 },
  });
  
  // ============================================================
  // SIGN-OFF
  // ============================================================
  const signY = (doc as any).lastAutoTable?.finalY + 20 || finalY + 80;
  doc.line(14, signY, 80, signY);
  doc.line(120, signY, 190, signY);
  doc.setFontSize(9);
  doc.setTextColor(0, 0, 0);
  doc.text('Operations Officer', 14, signY + 7);
  doc.text('Chief Flight Instructor', 120, signY + 7);
  
  // Footer
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text(`Generated by FlightPro Manager | ${new Date().toLocaleString('en-IN')}`, 14, 285);
  
  // Save
  doc.save(`Daily_Ops_${date}.pdf`);
}