// lib/pdf.ts
// PDF generation service for student logbooks and the Daily Flying Report
// Uses jsPDF for PDF creation and jsPDF-AutoTable for tables

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { FlightRecord, StudentRecord } from '@/types';

/**
 * Generate a student logbook PDF with all flight records
 * Includes student info, flight history table, totals, and instructor sign-off
 * 
 * @param student - The student's details
 * @param flights - Array of flight records for this student
 */
export function generateStudentLogbook(student: StudentRecord, flights: FlightRecord[]): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // ============================================================
  // HEADER
  // ============================================================
  doc.setFillColor(30, 41, 59); // Dark navy background
  doc.rect(0, 0, pageWidth, 35, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('FlightPro Manager - Student Logbook', 14, 15);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated: ${new Date().toLocaleDateString('en-IN')}`, 14, 25);
  
  // ============================================================
  // STUDENT INFORMATION
  // ============================================================
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Student Information', 14, 45);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const studentInfo = [
    `Name: ${student.name}`,
    `Enrollment ID: ${student.enrollmentId}`,
    `Training Stage: ${student.trainingStage}`,
    `Total Hours: ${student.totalHours}h`,
    `Medical Expiry: ${student.medicalExpiry || 'N/A'}`,
  ];
  studentInfo.forEach((line, i) => {
    doc.text(line, 14, 55 + i * 7);
  });
  
  // ============================================================
  // FLIGHT RECORDS TABLE
  // ============================================================
  const tableData = flights.map(f => [
    new Date(f.flightDate).toLocaleDateString('en-IN'),
    f.aircraftReg || 'N/A',
    `${f.departureTime?.slice(0, 5) || '--'} - ${f.arrivalTime?.slice(0, 5) || '--'}`,
    f.totalHours?.toFixed(1) || '0',
    f.landings?.toString() || '0',
    f.flightType || 'N/A',
    f.sortieType?.replace(/_/g, ' ') || 'N/A',
    f.instructorName || 'N/A',
    '⭐'.repeat(f.studentPerformance || 0),
  ]);
  
  autoTable(doc, {
    startY: 95,
    head: [['Date', 'Aircraft', 'Time', 'Hrs', 'Ldgs', 'Type', 'Sortie', 'Instructor', 'Perf']],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: [30, 41, 59],
      textColor: [255, 255, 255],
      fontSize: 8,
      fontStyle: 'bold',
    },
    bodyStyles: {
      fontSize: 8,
      textColor: [0, 0, 0],
    },
    alternateRowStyles: {
      fillColor: [241, 245, 249],
    },
    margin: { left: 14, right: 14 },
  });
  
  // ============================================================
  // SUMMARY
  // ============================================================
  const totalHours = flights.reduce((sum, f) => sum + (f.totalHours || 0), 0);
  const totalLandings = flights.reduce((sum, f) => sum + (f.landings || 0), 0);
  const soloHours = flights.filter(f => f.flightType === 'SOLO').reduce((sum, f) => sum + (f.totalHours || 0), 0);
  const dualHours = flights.filter(f => f.flightType === 'DUAL').reduce((sum, f) => sum + (f.totalHours || 0), 0);
  
  const finalY = (doc as any).lastAutoTable?.finalY || 150;
  
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Flight Summary', 14, finalY + 15);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const summary = [
    `Total Flights: ${flights.length}`,
    `Total Hours: ${totalHours.toFixed(1)}h`,
    `Total Landings: ${totalLandings}`,
    `Solo Hours: ${soloHours.toFixed(1)}h`,
    `Dual Hours: ${dualHours.toFixed(1)}h`,
  ];
  summary.forEach((line, i) => {
    doc.text(line, 14, finalY + 25 + i * 7);
  });
  
  // ============================================================
  // SIGN-OFF SECTION
  // ============================================================
  const signY = finalY + 70;
  doc.line(14, signY, 80, signY);
  doc.line(120, signY, 190, signY);
  doc.setFontSize(9);
  doc.text('Student Signature', 14, signY + 7);
  doc.text('Chief Flight Instructor', 120, signY + 7);
  
  // ============================================================
  // FOOTER
  // ============================================================
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text(`Generated by FlightPro Manager | ${new Date().toLocaleString('en-IN')}`, 14, 285);
  
  // Save the PDF
  doc.save(`${student.name.replace(/\s+/g, '_')}_Logbook.pdf`);
}

/**
 * Generate the FTO Daily Flying Report PDF — the exact format supplied by
 * the FTO: a header (Date/Airport), a per-flight table, and a footer
 * block of day-level totals. Operates on an already-computed
 * DailyFlyingReport (see app/api/reports/daily-flying/route.ts for how
 * rows/stats are derived) rather than raw records, so the PDF always
 * matches whatever was actually saved/reviewed on screen.
 *
 * Supersedes the old generateDailyOpsSheet, which was built earlier but
 * never wired up to any button — this is its real replacement, shaped to
 * the FTO's actual specified format instead of a guessed one.
 *
 * @param report - The generated/saved Daily Flying Report
 */
export function generateDailyFlyingReport(report: {
  reportDate: string;
  airportCode?: string;
  rows: { aircraft: string; student: string; instructor: string; sortie: string; start: string; end: string; hours: number; type: string; exercise: string; remarks: string }[];
  stats: {
    totalAircraftHours: number; totalStudentHours: number; totalInstructorHours: number;
    dualHours: number; soloHours: number; crossCountryHours: number; nightHours: number;
    aircraftGrounded: number; flightsCancelled: number; weatherCancellations: number;
    maintenanceCancellations: number; otherCancellations: number; safetyIncidents: number;
  };
  remarks?: string;
}): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // ============================================================
  // HEADER
  // ============================================================
  doc.setFillColor(30, 41, 59);
  doc.rect(0, 0, pageWidth, 30, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('FTO Daily Flying Report', 14, 15);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  const dateLabel = new Date(report.reportDate).toLocaleDateString('en-IN', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' });
  doc.text(`Date: ${dateLabel}`, 14, 24);
  doc.text(`Airport: ${report.airportCode || 'N/A'}`, pageWidth - 14, 24, { align: 'right' });

  // ============================================================
  // FLIGHT TABLE
  // ============================================================
  const tableData = report.rows.map(r => [
    r.aircraft, r.student, r.instructor, r.sortie, r.start, r.end,
    r.hours.toFixed(1), r.type, r.exercise, r.remarks,
  ]);

  autoTable(doc, {
    startY: 38,
    head: [['Aircraft', 'Student', 'Instructor', 'Sortie', 'Start', 'End', 'Hours', 'Dual/Solo', 'Exercise', 'Remarks']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: [30, 41, 59], textColor: [255, 255, 255], fontSize: 7, fontStyle: 'bold' },
    bodyStyles: { fontSize: 7, textColor: [0, 0, 0] },
    alternateRowStyles: { fillColor: [241, 245, 249] },
    margin: { left: 14, right: 14 },
  });

  // ============================================================
  // FOOTER SUMMARY
  // ============================================================
  const finalY = (doc as any).lastAutoTable?.finalY || 45;
  const s = report.stats;
  const summaryLines = [
    `Total Aircraft Hours: ${s.totalAircraftHours.toFixed(1)}h`,
    `Total Student Flying Hours: ${s.totalStudentHours.toFixed(1)}h`,
    `Total Instructor Hours: ${s.totalInstructorHours.toFixed(1)}h`,
    `Dual Hours: ${s.dualHours.toFixed(1)}h`,
    `Solo Hours: ${s.soloHours.toFixed(1)}h`,
    `Cross-Country Hours: ${s.crossCountryHours.toFixed(1)}h`,
    `Night Hours: ${s.nightHours.toFixed(1)}h`,
    `Aircraft Grounded: ${s.aircraftGrounded}`,
    `Flights Cancelled: ${s.flightsCancelled}`,
    `  Weather Cancellations: ${s.weatherCancellations}`,
    `  Maintenance Cancellations: ${s.maintenanceCancellations}`,
    `  Other Cancellations: ${s.otherCancellations}`,
    `Safety Incidents: ${s.safetyIncidents}`,
  ];

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text('Summary', 14, finalY + 12);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  const colSplit = Math.ceil(summaryLines.length / 2);
  summaryLines.slice(0, colSplit).forEach((line, i) => doc.text(line, 14, finalY + 20 + i * 6));
  summaryLines.slice(colSplit).forEach((line, i) => doc.text(line, 105, finalY + 20 + i * 6));

  const remarksY = finalY + 20 + colSplit * 6 + 8;
  doc.setFont('helvetica', 'bold');
  doc.text('Remarks:', 14, remarksY);
  doc.setFont('helvetica', 'normal');
  const remarksText = doc.splitTextToSize(report.remarks?.trim() || 'None', pageWidth - 28);
  doc.text(remarksText, 14, remarksY + 7);

  // ============================================================
  // SIGN-OFF
  // ============================================================
  const signY = remarksY + 7 + remarksText.length * 5 + 15;
  doc.line(14, signY, 80, signY);
  doc.line(120, signY, 190, signY);
  doc.setFontSize(9);
  doc.text('Operations Officer', 14, signY + 7);
  doc.text('Chief Flight Instructor', 120, signY + 7);

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text(`Generated by FlightPro Manager | ${new Date().toLocaleString('en-IN')}`, 14, 290);

  doc.save(`Daily_Flying_Report_${report.reportDate}.pdf`);
}