--
-- PostgreSQL database dump
--

\restrict oeXTRM7DjqUY5cN2PA98Az2Cl4aLWzfPbOSONM19Myexjlr7MY52wlcciSZ9uXB

-- Dumped from database version 17.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- Name: increment_student_hours(text, numeric, date); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.increment_student_hours(p_student_id text, p_hours numeric, p_first_solo_date date DEFAULT NULL::date) RETURNS void
    LANGUAGE sql
    AS $$
  update public.students
  set total_hours = coalesce(total_hours, 0) + p_hours,
      first_solo_date = coalesce(first_solo_date, p_first_solo_date)
  where id::text = p_student_id;
$$;


--
-- Name: next_enrollment_id(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.next_enrollment_id() RETURNS text
    LANGUAGE plpgsql
    AS $$
declare
  v_prefix text;
  v_width  integer;
  v_n      integer;
begin
  update public.enrollment_series
     set next_number = next_number + 1
   where is_current
  returning prefix, width, next_number - 1 into v_prefix, v_width, v_n;

  if v_prefix is null then
    return null;
  end if;

  return v_prefix || case when length(v_n::text) >= v_width then v_n::text
                          else lpad(v_n::text, v_width, '0') end;
end;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: aircraft; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.aircraft (
    id bigint NOT NULL,
    registration text DEFAULT 'NOT NULL'::text NOT NULL,
    type text DEFAULT 'NOT NULL'::text,
    model text,
    year integer,
    hobbs_time real DEFAULT '0'::real,
    fuel_capacity integer DEFAULT 200,
    current_fuel integer DEFAULT 200,
    status text DEFAULT 'ACTIVE'::text,
    next_maintenance text,
    created_at timestamp with time zone DEFAULT now(),
    fuel_burn_rate_lph numeric,
    is_simulator boolean DEFAULT false NOT NULL,
    log_book_serial_no text
);


--
-- Name: COLUMN aircraft.type; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.aircraft.type IS 'Engine category: ''Single Engine'' or ''Multi Engine''. Drives Multi Engine Hours classification on the Progress page and the fuel-burn-rate default. The SPECIFIC model/variant now lives in `model` (free text, e.g. "Cessna 172S Skyhawk") — `type` used to hold that instead, which is what this migration fixed.';


--
-- Name: COLUMN aircraft.model; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.aircraft.model IS 'Free-text specific model/variant, e.g. "Cessna 172S Skyhawk", "Piper Seneca II", "Diamond DA42 Twin Star". Display/identification only — not used in any lookup table.';


--
-- Name: COLUMN aircraft.fuel_burn_rate_lph; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.aircraft.fuel_burn_rate_lph IS 'This aircraft''s own average cruise fuel burn in liters/hour, if set. NULL = fall back to the built-in per-type default (see FUEL_BURN_RATE_BY_TYPE_LPH in lib/store.ts), then a flat 30 L/hr. Planning/scheduling estimate only, not a certified POH figure — verify per aircraft.';


--
-- Name: COLUMN aircraft.is_simulator; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.aircraft.is_simulator IS 'True if this row represents a flight simulator/training device rather than a real aircraft. Any flight_records row logged against an is_simulator=true aircraft counts toward a student''s Simulator Hours on the Progress page.';


--
-- Name: COLUMN aircraft.log_book_serial_no; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.aircraft.log_book_serial_no IS 'DGCA maintenance log: serial of the physical airframe log book volume this register corresponds to. PLACEHOLDER — label and format not yet verified against a real log book cover. Optional; the report omits the line when unset.';


--
-- Name: aircraft_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.aircraft ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.aircraft_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: aircraft_maintenance_schedule_templates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.aircraft_maintenance_schedule_templates (
    id bigint NOT NULL,
    aircraft_model text NOT NULL,
    item_name text NOT NULL,
    interval_type text NOT NULL,
    interval_value numeric NOT NULL,
    notes text,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    engine_type text,
    CONSTRAINT aircraft_maintenance_schedule_templates_engine_type_check CHECK (((engine_type = ANY (ARRAY['Single Engine'::text, 'Multi Engine'::text])) OR (engine_type IS NULL))),
    CONSTRAINT aircraft_maintenance_schedule_templates_interval_type_check CHECK ((interval_type = ANY (ARRAY['HOBBS_HOURS'::text, 'CALENDAR_MONTHS'::text]))),
    CONSTRAINT aircraft_maintenance_schedule_templates_interval_value_check CHECK ((interval_value > (0)::numeric))
);


--
-- Name: TABLE aircraft_maintenance_schedule_templates; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.aircraft_maintenance_schedule_templates IS 'Recurring maintenance items (engine TBO, inspections, etc.) per aircraft model. Referenced when an aircraft''s model is set/changed to compute due/overdue status (Phase 1: warnings only, no scheduling block). One row per (model, item).';


--
-- Name: COLUMN aircraft_maintenance_schedule_templates.aircraft_model; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.aircraft_maintenance_schedule_templates.aircraft_model IS 'Free-text model label — matched against aircraft.model. Also doubles as the source list for the Aircraft Model dropdown (with an "Other" free-text fallback) in AircraftFormModal/AircraftSetupTab.';


--
-- Name: COLUMN aircraft_maintenance_schedule_templates.interval_type; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.aircraft_maintenance_schedule_templates.interval_type IS 'HOBBS_HOURS: due every interval_value hobbs hours since the item''s last completion/baseline. CALENDAR_MONTHS: due every interval_value months since the same.';


--
-- Name: COLUMN aircraft_maintenance_schedule_templates.interval_value; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.aircraft_maintenance_schedule_templates.interval_value IS 'Hours (if HOBBS_HOURS) or months (if CALENDAR_MONTHS) between recurrences.';


--
-- Name: COLUMN aircraft_maintenance_schedule_templates.notes; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.aircraft_maintenance_schedule_templates.notes IS 'Source/caveat for this figure — engine manufacturer TBO figures are global and reliable; airframe inspection cadence is FTO/CAMP-programme specific and should be confirmed against the operator''s approved maintenance programme, not assumed from this seed data.';


--
-- Name: COLUMN aircraft_maintenance_schedule_templates.is_active; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.aircraft_maintenance_schedule_templates.is_active IS 'Soft-disable a template row without deleting it (preserves history/foreign-key-free references from any already-created maintenance_records).';


--
-- Name: COLUMN aircraft_maintenance_schedule_templates.engine_type; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.aircraft_maintenance_schedule_templates.engine_type IS 'Which Aircraft Type (Single Engine / Multi Engine) this model belongs to — used to filter the Model dropdown in AircraftFormModal/AircraftSetupTab down to only models matching the selected Type. Same value expected across every row for a given aircraft_model (the AircraftMaintenanceScheduleTab UI keeps them in sync). NULL means "unknown/not set" — the model is then shown for either Type, same as before this column existed.';


--
-- Name: aircraft_maintenance_schedule_templates_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.aircraft_maintenance_schedule_templates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.aircraft_maintenance_schedule_templates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ames; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ames (
    id bigint NOT NULL,
    name text NOT NULL,
    license_no text NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: ames_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ames ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.ames_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: availability; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.availability (
    id bigint NOT NULL,
    person_type text NOT NULL,
    person_id text NOT NULL,
    leave_type text DEFAULT 'UNAVAILABLE'::text,
    start_date date NOT NULL,
    end_date date NOT NULL,
    start_time time without time zone,
    end_time time without time zone,
    reason text DEFAULT ''::text,
    status text DEFAULT 'APPROVED'::text,
    created_by text DEFAULT ''::text,
    created_at timestamp with time zone DEFAULT now(),
    pending_change jsonb,
    needs_admin_approval boolean DEFAULT false NOT NULL,
    CONSTRAINT availability_leave_type_check CHECK ((leave_type = ANY (ARRAY['UNAVAILABLE'::text, 'VACATION'::text, 'SICK'::text, 'TRAINING'::text, 'PERSONAL'::text]))),
    CONSTRAINT availability_person_type_check CHECK ((person_type = ANY (ARRAY['instructor'::text, 'student'::text]))),
    CONSTRAINT availability_status_check CHECK ((status = ANY (ARRAY['APPROVED'::text, 'PENDING'::text, 'CANCELLED'::text])))
);


--
-- Name: availability_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.availability ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.availability_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ba_tests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ba_tests (
    id bigint NOT NULL,
    test_date date NOT NULL,
    aircraft_id text,
    aircraft_reg text,
    safety_officer_id text,
    safety_officer_name text NOT NULL,
    person_type text NOT NULL,
    person_id text,
    person_name text NOT NULL,
    license_number text,
    reporting_time text,
    ba_time text,
    ba_percentage numeric,
    ba_equipment text,
    recorded_by text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ba_tests_person_type_check CHECK ((person_type = ANY (ARRAY['STUDENT'::text, 'INSTRUCTOR'::text])))
);


--
-- Name: TABLE ba_tests; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.ba_tests IS 'Pre-flight Breath Analyser (BA) test log per CAR Section 5, Series F, Part III — the Breath Analyser Register on the Reports page. One row per person tested. Editable/correctable after creation (updated_at), unlike the append-only safety_incidents log this table otherwise mirrors in shape.';


--
-- Name: ba_tests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ba_tests ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.ba_tests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: daily_flying_reports; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.daily_flying_reports (
    id bigint NOT NULL,
    report_date date NOT NULL,
    airport_code text,
    rows jsonb DEFAULT '[]'::jsonb NOT NULL,
    stats jsonb DEFAULT '{}'::jsonb NOT NULL,
    remarks text DEFAULT ''::text NOT NULL,
    generated_by text,
    generated_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE daily_flying_reports; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.daily_flying_reports IS 'One saved snapshot per calendar date (report_date is UNIQUE) — the flight rows, computed footer stats, and free-text remarks as they stood when the report was generated. Re-generating a date overwrites its snapshot (deliberate — lets a mistake be corrected before sign-off). Not recalculated live on every view, so a past day''s report cannot silently drift if the underlying flight records are edited later.';


--
-- Name: daily_flying_reports_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.daily_flying_reports ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.daily_flying_reports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: enrollment_series; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.enrollment_series (
    prefix text NOT NULL,
    start_number integer NOT NULL,
    width integer NOT NULL,
    next_number integer NOT NULL,
    is_current boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT enrollment_series_start_number_check CHECK ((start_number >= 0)),
    CONSTRAINT enrollment_series_width_check CHECK (((width >= 1) AND (width <= 9)))
);


--
-- Name: exercises; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.exercises (
    id bigint NOT NULL,
    exercise_name text NOT NULL,
    short_code text NOT NULL,
    full_description text DEFAULT ''::text,
    is_active boolean DEFAULT true,
    sort_order integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: exercises_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.exercises ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.exercises_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flight_records; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.flight_records (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    student_id uuid NOT NULL,
    aircraft_id bigint NOT NULL,
    instructor_id text NOT NULL,
    flight_date date DEFAULT CURRENT_DATE NOT NULL,
    departure_time time without time zone NOT NULL,
    arrival_time time without time zone NOT NULL,
    hobbs_start numeric(6,1) DEFAULT 0,
    hobbs_end numeric(6,1) DEFAULT 0,
    landings integer DEFAULT 1,
    flight_type text DEFAULT 'DUAL'::text,
    sortie_type text DEFAULT 'CIRCUIT_DUAL'::text,
    maneuvers text DEFAULT ''::text,
    instructor_notes text DEFAULT ''::text,
    student_performance integer DEFAULT 3,
    weather_conditions text DEFAULT ''::text,
    created_at timestamp with time zone DEFAULT now(),
    exercise text,
    picus_hours numeric,
    total_hours numeric
);


--
-- Name: COLUMN flight_records.picus_hours; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.flight_records.picus_hours IS 'DGCA PICUS: hours the STUDENT acted as Pilot in Command Under Supervision on a DUAL sortie. NULL = not marked as student-PIC (the default for every historical row); 0 = marked but no PIC time flown. Solo sorties do NOT use this column — their PIC time is the whole flight and is derived from total_hours. Summed with solo hours into the Progress page PIC metric.';


--
-- Name: fto_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fto_settings (
    id bigint NOT NULL,
    setting_key text NOT NULL,
    setting_value text DEFAULT ''::text,
    description text DEFAULT ''::text,
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: fto_settings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fto_settings ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.fto_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fuel_records; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fuel_records (
    id bigint NOT NULL,
    aircraft_id bigint NOT NULL,
    refueling_date timestamp with time zone DEFAULT now(),
    fuel_added_liters integer NOT NULL,
    fuel_cost_per_liter numeric(10,2) DEFAULT 145.00,
    fuel_level_before integer DEFAULT 0,
    fuel_level_after integer DEFAULT 0,
    fuel_type text DEFAULT 'AVGAS 100LL'::text,
    refueled_by text DEFAULT ''::text,
    notes text DEFAULT ''::text,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: fuel_records_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fuel_records ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.fuel_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: general_weather_cache; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.general_weather_cache (
    id bigint NOT NULL,
    cache_key text NOT NULL,
    temperature numeric NOT NULL,
    dewpoint numeric NOT NULL,
    wind_direction numeric NOT NULL,
    wind_speed numeric NOT NULL,
    pressure numeric NOT NULL,
    cloud_cover numeric NOT NULL,
    condition_text text NOT NULL,
    observed_at timestamp with time zone NOT NULL,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: general_weather_cache_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.general_weather_cache ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.general_weather_cache_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ground_school_classes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ground_school_classes (
    id bigint NOT NULL,
    subject_id bigint,
    instructor_id text,
    class_date date NOT NULL,
    start_time time without time zone,
    end_time time without time zone,
    topic text DEFAULT ''::text,
    notes text DEFAULT ''::text,
    status text DEFAULT 'SCHEDULED'::text,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: ground_school_classes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ground_school_classes ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.ground_school_classes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ground_school_enrollment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ground_school_enrollment (
    id bigint NOT NULL,
    class_id bigint,
    student_id uuid,
    attendance_status text DEFAULT 'PENDING'::text,
    exam_date date,
    exam_score numeric(5,2),
    exam_result text,
    attempts integer DEFAULT 0,
    examiner text DEFAULT ''::text,
    notes text DEFAULT ''::text,
    created_at timestamp with time zone DEFAULT now(),
    dgca_roll_number text
);


--
-- Name: COLUMN ground_school_enrollment.dgca_roll_number; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.ground_school_enrollment.dgca_roll_number IS 'The student''s DGCA roll number for this subject''s exam. Required by the app when recording a PASS (Direct Exam Entry on Ground School -> Progress, or the attendance page''s exam editor) — nullable here since rows exist in pre-exam states (PENDING, etc.) where it doesn''t apply yet.';


--
-- Name: ground_school_enrollment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ground_school_enrollment ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.ground_school_enrollment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ground_school_subjects; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ground_school_subjects (
    id bigint NOT NULL,
    subject_name text NOT NULL,
    subject_code text NOT NULL,
    validity_years numeric(3,1),
    required_before_hours integer,
    is_mandatory boolean DEFAULT true,
    sort_order integer DEFAULT 0,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: ground_school_subjects_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ground_school_subjects ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.ground_school_subjects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: holidays; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.holidays (
    id bigint NOT NULL,
    holiday_name text NOT NULL,
    holiday_date date NOT NULL,
    is_recurring boolean DEFAULT false NOT NULL,
    notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE holidays; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.holidays IS 'FTO-wide blackout dates. Flight bookings and ground-school classes cannot be scheduled on a date matching a row here. is_recurring=true matches by month/day every year; is_recurring=false matches the exact holiday_date only.';


--
-- Name: holidays_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.holidays ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.holidays_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: instructor_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.instructor_roles (
    id bigint NOT NULL,
    role_name text NOT NULL,
    role_code text NOT NULL,
    description text DEFAULT ''::text,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: instructor_roles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.instructor_roles ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.instructor_roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: instructor_roster; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.instructor_roster (
    id bigint NOT NULL,
    instructor_id bigint NOT NULL,
    weekday smallint NOT NULL,
    start_time time without time zone,
    end_time time without time zone,
    updated_by text DEFAULT ''::text,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT instructor_roster_times_check CHECK ((((start_time IS NULL) AND (end_time IS NULL)) OR ((start_time IS NOT NULL) AND (end_time IS NOT NULL) AND (end_time > start_time)))),
    CONSTRAINT instructor_roster_weekday_check CHECK (((weekday >= 0) AND (weekday <= 6)))
);


--
-- Name: instructor_roster_exceptions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.instructor_roster_exceptions (
    id bigint NOT NULL,
    instructor_id bigint NOT NULL,
    date date NOT NULL,
    start_time time without time zone,
    end_time time without time zone,
    note text DEFAULT ''::text,
    created_by text DEFAULT ''::text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT instructor_roster_exceptions_times_check CHECK ((((start_time IS NULL) AND (end_time IS NULL)) OR ((start_time IS NOT NULL) AND (end_time IS NOT NULL) AND (end_time > start_time))))
);


--
-- Name: instructor_roster_exceptions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.instructor_roster_exceptions ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.instructor_roster_exceptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: instructor_roster_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.instructor_roster ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.instructor_roster_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: instructors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.instructors (
    id bigint NOT NULL,
    name text NOT NULL,
    initials text NOT NULL,
    license_number text NOT NULL,
    ratings text DEFAULT 'CFI'::text,
    max_daily_hours integer DEFAULT 8,
    email text DEFAULT ''::text,
    phone text DEFAULT ''::text,
    status text DEFAULT 'AVAILABLE'::text,
    created_at timestamp with time zone DEFAULT now(),
    can_self_book boolean DEFAULT false NOT NULL,
    license_expiry_date date,
    license_issue_date date,
    employment_status text DEFAULT 'ACTIVE'::text NOT NULL,
    off_duty_date date,
    last_working_date date,
    joining_date date,
    CONSTRAINT instructors_employment_status_check CHECK ((employment_status = ANY (ARRAY['ACTIVE'::text, 'INACTIVE'::text])))
);


--
-- Name: COLUMN instructors.can_self_book; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.instructors.can_self_book IS 'Whether this instructor can create their own new Schedule bookings. false by default — a super_admin grants it per instructor from the Instructors tab. Does not affect viewing the Schedule or editing/debriefing/cancelling flights already assigned to them.';


--
-- Name: COLUMN instructors.license_expiry_date; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.instructors.license_expiry_date IS 'Expiry date of the instructor''s CPL (Commercial Pilot License) / License Number.';


--
-- Name: COLUMN instructors.license_issue_date; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.instructors.license_issue_date IS 'Issue date of the instructor''s CPL (Commercial Pilot License) / License Number.';


--
-- Name: instructors_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.instructors ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.instructors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: login_audit; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.login_audit (
    id bigint NOT NULL,
    user_email text NOT NULL,
    login_status text NOT NULL,
    ip_address text DEFAULT ''::text,
    user_agent text DEFAULT ''::text,
    attempted_at timestamp with time zone DEFAULT now(),
    CONSTRAINT login_audit_login_status_check CHECK ((login_status = ANY (ARRAY['SUCCESS'::text, 'FAILED'::text])))
);


--
-- Name: login_audit_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.login_audit ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.login_audit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: maintenance_records; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.maintenance_records (
    id bigint NOT NULL,
    aircraft_id bigint NOT NULL,
    maintenance_type text NOT NULL,
    description text DEFAULT ''::text,
    scheduled_date date NOT NULL,
    completed_date date,
    status text DEFAULT 'SCHEDULED'::text,
    cost numeric(10,2) DEFAULT 0,
    performed_by text DEFAULT ''::text,
    notes text DEFAULT ''::text,
    created_at timestamp with time zone DEFAULT now(),
    maintenance_start timestamp with time zone,
    maintenance_end timestamp with time zone,
    hobbs_at_completion numeric,
    reported_by text,
    is_squawk boolean DEFAULT false NOT NULL,
    ticket_number text,
    parts_used text,
    ame_name text,
    ame_license_no text,
    crs_reference text,
    is_baseline boolean DEFAULT false NOT NULL
);


--
-- Name: COLUMN maintenance_records.maintenance_start; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.maintenance_records.maintenance_start IS 'When the aircraft actually goes out of service. NULL = legacy/simple record, blocks the whole scheduled_date day.';


--
-- Name: COLUMN maintenance_records.maintenance_end; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.maintenance_records.maintenance_end IS 'When the aircraft is back in service. NULL with maintenance_start set = open-ended (in-progress, finish time unknown) — blocks indefinitely until set or the record is marked COMPLETED. May be any number of days after maintenance_start.';


--
-- Name: COLUMN maintenance_records.hobbs_at_completion; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.maintenance_records.hobbs_at_completion IS 'Aircraft hobbs reading at the time this record was completed (or, for a baseline row entered when enabling schedule tracking, the hobbs reading at last known service). Nullable — most historical records predate this feature and CALENDAR_MONTHS-only items never need it.';


--
-- Name: COLUMN maintenance_records.is_squawk; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.maintenance_records.is_squawk IS 'True when this record was filed by a pilot (instructor/student) via the "Report a Defect" page, not logged by maintenance staff.';


--
-- Name: COLUMN maintenance_records.ticket_number; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.maintenance_records.ticket_number IS 'Auto-generated, year-scoped (RMT-<year>-NNN staff-logged, IMT-<year>-NNN pilot squawk per is_squawk), assigned on insert. Generated in app/api/maintenance-records/route.ts.';


--
-- Name: COLUMN maintenance_records.parts_used; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.maintenance_records.parts_used IS 'DGCA maintenance log: parts/materials consumed on this job, free text. Set via the Log Maintenance form when status = COMPLETED.';


--
-- Name: COLUMN maintenance_records.ame_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.maintenance_records.ame_name IS 'DGCA maintenance log: name of the AME certifying the release to service. Free text — external/contract AMEs have no user row.';


--
-- Name: COLUMN maintenance_records.ame_license_no; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.maintenance_records.ame_license_no IS 'DGCA maintenance log: certifying AME licence number and category. The identifying field on a DGCA audit.';


--
-- Name: COLUMN maintenance_records.crs_reference; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.maintenance_records.crs_reference IS 'DGCA maintenance log: Certificate of Release to Service reference number. The app RECORDS the CRS; it does not issue one — the signature stays on paper.';


--
-- Name: COLUMN maintenance_records.is_baseline; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.maintenance_records.is_baseline IS 'True for a synthetic "Set Baseline" row that anchors maintenance-schedule due dates without any work having been performed. Excluded from the DGCA Maintenance Log report — see app/dashboard/reports/maintenance-log/page.tsx.';


--
-- Name: maintenance_records_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.maintenance_records ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.maintenance_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notam_cache; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notam_cache (
    id bigint NOT NULL,
    cache_key text NOT NULL,
    notams jsonb NOT NULL,
    total_count integer DEFAULT 0 NOT NULL,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE notam_cache; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.notam_cache IS 'Shared cache for SkyLink NOTAM responses. TTL is configurable via the fto_settings key notam_cache_ttl_hours (default 2). One row per ICAO station, upserted in place; no clearing job required.';


--
-- Name: notam_cache_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notam_cache ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.notam_cache_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notification_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notification_log (
    id bigint NOT NULL,
    type text NOT NULL,
    subject text NOT NULL,
    message text NOT NULL,
    sent_to text DEFAULT ''::text,
    sent_at timestamp with time zone DEFAULT now()
);


--
-- Name: notification_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notification_log ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.notification_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: password_reset_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.password_reset_tokens (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    token text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: password_reset_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.password_reset_tokens ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.password_reset_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: safety_incidents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.safety_incidents (
    id bigint NOT NULL,
    incident_date date NOT NULL,
    incident_time text,
    aircraft_id text,
    aircraft_reg text,
    student_id text,
    student_name text,
    instructor_id text,
    instructor_name text,
    description text NOT NULL,
    severity text DEFAULT 'MINOR'::text NOT NULL,
    reported_by text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    risk_severity smallint,
    risk_likelihood smallint,
    risk_score smallint,
    status text DEFAULT 'OPEN'::text NOT NULL,
    corrective_action text,
    assigned_to text,
    closed_by text,
    closed_at timestamp with time zone,
    incident_number text,
    category text DEFAULT 'OTHER'::text NOT NULL,
    resolution_note text,
    resolved_by text,
    resolved_at timestamp with time zone,
    CONSTRAINT safety_incidents_category_check CHECK ((category = ANY (ARRAY['BIRD_STRIKE'::text, 'MECHANICAL_SYSTEMS'::text, 'OTHER_TECHNICAL'::text, 'OPERATIONAL'::text, 'OTHER'::text]))),
    CONSTRAINT safety_incidents_risk_likelihood_check CHECK (((risk_likelihood >= 1) AND (risk_likelihood <= 5))),
    CONSTRAINT safety_incidents_risk_severity_check CHECK (((risk_severity >= 1) AND (risk_severity <= 5))),
    CONSTRAINT safety_incidents_severity_check CHECK ((severity = ANY (ARRAY['MINOR'::text, 'MAJOR'::text, 'CRITICAL'::text]))),
    CONSTRAINT safety_incidents_status_check CHECK ((status = ANY (ARRAY['OPEN'::text, 'IN_PROGRESS'::text, 'RESOLVED'::text, 'CLOSED'::text])))
);


--
-- Name: TABLE safety_incidents; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.safety_incidents IS 'Minimal safety incident log — date, who/what was involved, a description, and a severity. Feeds the Daily Flying Report''s "Safety incidents" count. Not the full DGCA-format Incident Report (a separate, larger report, not yet built) — this is deliberately lightweight, extendable later without a breaking change.';


--
-- Name: COLUMN safety_incidents.risk_score; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.safety_incidents.risk_score IS 'severity * likelihood (1-25), ICAO Doc 9859 5x5 matrix. Denormalized for filtering/sorting.';


--
-- Name: COLUMN safety_incidents.status; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.safety_incidents.status IS 'OPEN (just logged, not yet triaged) -> IN_PROGRESS (risk rated / corrective action underway) -> CLOSED (corrective action complete).';


--
-- Name: COLUMN safety_incidents.incident_number; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.safety_incidents.incident_number IS 'Auto-generated, year-scoped (INC-<year>-NNN), assigned on report. Generated in app/api/safety-incidents/route.ts.';


--
-- Name: COLUMN safety_incidents.category; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.safety_incidents.category IS 'BIRD_STRIKE/MECHANICAL_SYSTEMS/OTHER_TECHNICAL are "technical" — auto-suggest assigned_to=Maintenance on report. See lib/permissions.ts TECHNICAL_INCIDENT_CATEGORIES.';


--
-- Name: COLUMN safety_incidents.resolution_note; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.safety_incidents.resolution_note IS 'Set by Maintenance via their narrow resolve action (INCIDENT_RESOLVE_ROLES) when marking status RESOLVED.';


--
-- Name: safety_incidents_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.safety_incidents ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.safety_incidents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: scheduled_flights; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.scheduled_flights (
    id bigint NOT NULL,
    aircraft_id bigint NOT NULL,
    instructor_id text NOT NULL,
    student_id uuid,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    sortie_type text DEFAULT 'CIRCUIT_DUAL'::text,
    status text DEFAULT 'SCHEDULED'::text,
    weather_briefed boolean DEFAULT false,
    notam_briefed boolean DEFAULT false,
    notes text DEFAULT ''::text,
    created_at timestamp with time zone DEFAULT now(),
    exercise text DEFAULT ''::text,
    cancellation_reason text,
    logbook_pending boolean DEFAULT false,
    pending_debrief jsonb,
    cancellation_note text,
    roster_override boolean DEFAULT false NOT NULL,
    CONSTRAINT scheduled_flights_cancellation_reason_check CHECK (((cancellation_reason IS NULL) OR (cancellation_reason = ANY (ARRAY['WEATHER'::text, 'MAINTENANCE'::text, 'ON_LEAVE'::text, 'REJECTED'::text, 'STUDENT_NO_SHOW'::text, 'INSTRUCTOR_UNAVAILABLE'::text, 'ATC_AIRSPACE'::text, 'OTHER'::text]))))
);


--
-- Name: COLUMN scheduled_flights.cancellation_reason; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.scheduled_flights.cancellation_reason IS 'Why this booking was cancelled — WEATHER, MAINTENANCE, or OTHER. NULL for flights that are not cancelled, or were cancelled before this column existed. Set by cancelFlight() in lib/store.ts, which now soft-cancels (UPDATE status=CANCELLED) instead of deleting the row.';


--
-- Name: COLUMN scheduled_flights.logbook_pending; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.scheduled_flights.logbook_pending IS 'True when this flight was checked out with "auto-create logbook entry" unchecked: the flight is COMPLETED but its logbook entry still needs to be finished from the Flights page using pending_debrief below.';


--
-- Name: COLUMN scheduled_flights.pending_debrief; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.scheduled_flights.pending_debrief IS 'JSONB snapshot of the debrief inputs captured at check-out when logbook_pending is true. NULL once the logbook entry is finished, or when the logbook entry was auto-created at check-out.';


--
-- Name: scheduled_flights_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.scheduled_flights ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.scheduled_flights_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sortie_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sortie_types (
    id bigint NOT NULL,
    type_name text NOT NULL,
    type_code text NOT NULL,
    color_hex text DEFAULT '#2563eb'::text,
    requires_instructor boolean DEFAULT true,
    requires_student boolean DEFAULT true,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: sortie_types_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sortie_types ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.sortie_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: students; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.students (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    enrollment_id text NOT NULL,
    name text NOT NULL,
    initials text NOT NULL,
    training_stage text DEFAULT 'PPL'::text,
    total_hours numeric(8,2) DEFAULT 0,
    medical_expiry text DEFAULT ''::text,
    email text DEFAULT ''::text,
    phone text DEFAULT ''::text,
    date_of_birth text DEFAULT ''::text,
    joined_date text DEFAULT ''::text,
    status text DEFAULT 'ACTIVE'::text,
    created_at timestamp with time zone DEFAULT now(),
    first_solo_date date,
    assigned_instructor_id text,
    spl_number text,
    spl_expiry_date date,
    spl_issue_date date,
    medical_issue_date date
);


--
-- Name: COLUMN students.spl_number; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.students.spl_number IS 'The student''s Student Pilot License (SPL) number. Shown as the "License Number" on the Breath Analyser Register when this student is the person tested. Nullable — not every student has flown solo/holds an SPL yet. Editable in the Add/Edit Student form (Students page).';


--
-- Name: COLUMN students.spl_expiry_date; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.students.spl_expiry_date IS 'Expiry date of the student''s Student Pilot License (SPL). Nullable — not every student has one filled in yet.';


--
-- Name: COLUMN students.spl_issue_date; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.students.spl_issue_date IS 'Issue date of the student''s Student Pilot License (SPL). Nullable — not every student has one filled in yet.';


--
-- Name: COLUMN students.medical_issue_date; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.students.medical_issue_date IS 'Issue date of the student''s DGCA Class 1 medical certificate. Nullable — not every student has one filled in yet.';


--
-- Name: training_programs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.training_programs (
    id bigint NOT NULL,
    program_name text NOT NULL,
    program_code text NOT NULL,
    required_hours integer DEFAULT 200,
    description text DEFAULT ''::text,
    is_active boolean DEFAULT true,
    sort_order integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT now(),
    solo_hours numeric,
    cross_country_hours numeric,
    instrument_hours numeric,
    night_hours numeric,
    landings_required integer,
    multi_engine_hours numeric,
    simulator_hours numeric
);


--
-- Name: COLUMN training_programs.solo_hours; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.training_programs.solo_hours IS 'Minimum solo hours required for this program. NULL = fall back to the built-in PPL/CPL default on the Progress page (see PPL_REQUIREMENTS/CPL_REQUIREMENTS in app/dashboard/progress/page.tsx).';


--
-- Name: COLUMN training_programs.cross_country_hours; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.training_programs.cross_country_hours IS 'Minimum cross-country hours required for this program. NULL = fall back to the built-in PPL/CPL default on the Progress page.';


--
-- Name: COLUMN training_programs.instrument_hours; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.training_programs.instrument_hours IS 'Minimum instrument hours required for this program. NULL = fall back to the built-in PPL/CPL default on the Progress page.';


--
-- Name: COLUMN training_programs.night_hours; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.training_programs.night_hours IS 'Minimum night hours required for this program. NULL = fall back to the built-in PPL/CPL default on the Progress page.';


--
-- Name: COLUMN training_programs.landings_required; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.training_programs.landings_required IS 'Minimum landings required for this program. NULL = fall back to the built-in PPL/CPL default on the Progress page.';


--
-- Name: COLUMN training_programs.multi_engine_hours; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.training_programs.multi_engine_hours IS 'Minimum Multi Engine hours required for this program. NULL = this metric does not apply to this program and its card is hidden on the Progress page (no built-in fallback, unlike solo/cross-country/instrument/night). Actual hours auto-total from flight_records logged against an aircraft with type = ''Multi Engine''.';


--
-- Name: COLUMN training_programs.simulator_hours; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.training_programs.simulator_hours IS 'Minimum Simulator hours required for this program. NULL = this metric does not apply to this program and its card is hidden on the Progress page. Actual hours auto-total from flight_records logged against an aircraft with is_simulator = true.';


--
-- Name: training_programs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.training_programs ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.training_programs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: training_requirement_templates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.training_requirement_templates (
    id bigint NOT NULL,
    program_code text NOT NULL,
    requirement_name text NOT NULL,
    requirement_category text,
    sort_order integer DEFAULT 99 NOT NULL,
    validity_years numeric,
    required_before_hours integer,
    blocks_solo boolean DEFAULT false NOT NULL,
    blocks_all_flights boolean DEFAULT false NOT NULL,
    notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE training_requirement_templates; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.training_requirement_templates IS 'Master requirement list per training program, managed in Admin Setup -> Requirements. Provisioned out to individual students (training_requirements) via "Sync to Students" / student creation — see lib/requirements-provisioning.ts. Editing a template here does NOT retroactively change requirements already assigned to students (intentional, preserves each student''s audit trail as of when they were provisioned).';


--
-- Name: training_requirement_templates_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.training_requirement_templates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.training_requirement_templates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: training_requirements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.training_requirements (
    id bigint NOT NULL,
    student_id uuid NOT NULL,
    requirement_name text NOT NULL,
    requirement_category text DEFAULT 'PPL'::text,
    is_completed boolean DEFAULT false,
    completed_date date,
    completed_by text DEFAULT ''::text,
    notes text DEFAULT ''::text,
    sort_order integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT now(),
    program_code text DEFAULT 'CPL'::text,
    required_before_hours integer,
    validity_years numeric(3,1),
    blocks_solo boolean DEFAULT false,
    blocks_all_flights boolean DEFAULT false,
    template_id bigint
);


--
-- Name: COLUMN training_requirements.template_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.training_requirements.template_id IS 'Which training_requirement_templates row this was provisioned from, if any. NULL for rows added directly to a student with no template. Best-effort backfilled by program_code + requirement_name match for rows that existed before this column did.';


--
-- Name: training_requirements_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.training_requirements ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.training_requirements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    email text NOT NULL,
    password_hash text NOT NULL,
    name text NOT NULL,
    role text DEFAULT 'instructor'::text,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    student_id uuid,
    force_password_reset boolean DEFAULT true,
    last_login timestamp with time zone,
    permission_overrides jsonb DEFAULT '{}'::jsonb NOT NULL,
    joining_date date,
    CONSTRAINT users_role_check CHECK ((role = ANY (ARRAY['admin'::text, 'instructor'::text, 'maintenance'::text, 'operations'::text, 'safety_officer'::text, 'student'::text, 'super_admin'::text])))
);


--
-- Name: aircraft_maintenance_schedule_templates aircraft_maintenance_schedule_templates_model_item_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.aircraft_maintenance_schedule_templates
    ADD CONSTRAINT aircraft_maintenance_schedule_templates_model_item_unique UNIQUE (aircraft_model, item_name);


--
-- Name: aircraft_maintenance_schedule_templates aircraft_maintenance_schedule_templates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.aircraft_maintenance_schedule_templates
    ADD CONSTRAINT aircraft_maintenance_schedule_templates_pkey PRIMARY KEY (id);


--
-- Name: aircraft aircraft_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.aircraft
    ADD CONSTRAINT aircraft_pkey PRIMARY KEY (id);


--
-- Name: ames ames_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ames
    ADD CONSTRAINT ames_pkey PRIMARY KEY (id);


--
-- Name: availability availability_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.availability
    ADD CONSTRAINT availability_pkey PRIMARY KEY (id);


--
-- Name: ba_tests ba_tests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ba_tests
    ADD CONSTRAINT ba_tests_pkey PRIMARY KEY (id);


--
-- Name: daily_flying_reports daily_flying_reports_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_flying_reports
    ADD CONSTRAINT daily_flying_reports_pkey PRIMARY KEY (id);


--
-- Name: daily_flying_reports daily_flying_reports_report_date_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_flying_reports
    ADD CONSTRAINT daily_flying_reports_report_date_key UNIQUE (report_date);


--
-- Name: enrollment_series enrollment_series_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enrollment_series
    ADD CONSTRAINT enrollment_series_pkey PRIMARY KEY (prefix);


--
-- Name: exercises exercises_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exercises
    ADD CONSTRAINT exercises_pkey PRIMARY KEY (id);


--
-- Name: exercises exercises_short_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exercises
    ADD CONSTRAINT exercises_short_code_key UNIQUE (short_code);


--
-- Name: flight_records flight_records_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flight_records
    ADD CONSTRAINT flight_records_pkey PRIMARY KEY (id);


--
-- Name: fto_settings fto_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fto_settings
    ADD CONSTRAINT fto_settings_pkey PRIMARY KEY (id);


--
-- Name: fto_settings fto_settings_setting_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fto_settings
    ADD CONSTRAINT fto_settings_setting_key_key UNIQUE (setting_key);


--
-- Name: fuel_records fuel_records_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fuel_records
    ADD CONSTRAINT fuel_records_pkey PRIMARY KEY (id);


--
-- Name: general_weather_cache general_weather_cache_cache_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.general_weather_cache
    ADD CONSTRAINT general_weather_cache_cache_key_key UNIQUE (cache_key);


--
-- Name: general_weather_cache general_weather_cache_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.general_weather_cache
    ADD CONSTRAINT general_weather_cache_pkey PRIMARY KEY (id);


--
-- Name: ground_school_classes ground_school_classes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ground_school_classes
    ADD CONSTRAINT ground_school_classes_pkey PRIMARY KEY (id);


--
-- Name: ground_school_enrollment ground_school_enrollment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ground_school_enrollment
    ADD CONSTRAINT ground_school_enrollment_pkey PRIMARY KEY (id);


--
-- Name: ground_school_subjects ground_school_subjects_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ground_school_subjects
    ADD CONSTRAINT ground_school_subjects_pkey PRIMARY KEY (id);


--
-- Name: ground_school_subjects ground_school_subjects_subject_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ground_school_subjects
    ADD CONSTRAINT ground_school_subjects_subject_code_key UNIQUE (subject_code);


--
-- Name: holidays holidays_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.holidays
    ADD CONSTRAINT holidays_pkey PRIMARY KEY (id);


--
-- Name: instructor_roles instructor_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.instructor_roles
    ADD CONSTRAINT instructor_roles_pkey PRIMARY KEY (id);


--
-- Name: instructor_roles instructor_roles_role_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.instructor_roles
    ADD CONSTRAINT instructor_roles_role_code_key UNIQUE (role_code);


--
-- Name: instructor_roles instructor_roles_role_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.instructor_roles
    ADD CONSTRAINT instructor_roles_role_name_key UNIQUE (role_name);


--
-- Name: instructor_roster_exceptions instructor_roster_exceptions_one_per_date; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.instructor_roster_exceptions
    ADD CONSTRAINT instructor_roster_exceptions_one_per_date UNIQUE (instructor_id, date);


--
-- Name: instructor_roster_exceptions instructor_roster_exceptions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.instructor_roster_exceptions
    ADD CONSTRAINT instructor_roster_exceptions_pkey PRIMARY KEY (id);


--
-- Name: instructor_roster instructor_roster_one_per_day; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.instructor_roster
    ADD CONSTRAINT instructor_roster_one_per_day UNIQUE (instructor_id, weekday);


--
-- Name: instructor_roster instructor_roster_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.instructor_roster
    ADD CONSTRAINT instructor_roster_pkey PRIMARY KEY (id);


--
-- Name: instructors instructors_initials_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.instructors
    ADD CONSTRAINT instructors_initials_key UNIQUE (initials);


--
-- Name: instructors instructors_license_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.instructors
    ADD CONSTRAINT instructors_license_number_key UNIQUE (license_number);


--
-- Name: instructors instructors_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.instructors
    ADD CONSTRAINT instructors_pkey PRIMARY KEY (id);


--
-- Name: login_audit login_audit_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.login_audit
    ADD CONSTRAINT login_audit_pkey PRIMARY KEY (id);


--
-- Name: maintenance_records maintenance_records_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.maintenance_records
    ADD CONSTRAINT maintenance_records_pkey PRIMARY KEY (id);


--
-- Name: notam_cache notam_cache_cache_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notam_cache
    ADD CONSTRAINT notam_cache_cache_key_key UNIQUE (cache_key);


--
-- Name: notam_cache notam_cache_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notam_cache
    ADD CONSTRAINT notam_cache_pkey PRIMARY KEY (id);


--
-- Name: notification_log notification_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_log
    ADD CONSTRAINT notification_log_pkey PRIMARY KEY (id);


--
-- Name: password_reset_tokens password_reset_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);


--
-- Name: password_reset_tokens password_reset_tokens_token_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_token_key UNIQUE (token);


--
-- Name: safety_incidents safety_incidents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.safety_incidents
    ADD CONSTRAINT safety_incidents_pkey PRIMARY KEY (id);


--
-- Name: scheduled_flights scheduled_flights_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scheduled_flights
    ADD CONSTRAINT scheduled_flights_pkey PRIMARY KEY (id);


--
-- Name: sortie_types sortie_types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sortie_types
    ADD CONSTRAINT sortie_types_pkey PRIMARY KEY (id);


--
-- Name: sortie_types sortie_types_type_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sortie_types
    ADD CONSTRAINT sortie_types_type_code_key UNIQUE (type_code);


--
-- Name: sortie_types sortie_types_type_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sortie_types
    ADD CONSTRAINT sortie_types_type_name_key UNIQUE (type_name);


--
-- Name: students students_enrollment_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_enrollment_id_key UNIQUE (enrollment_id);


--
-- Name: students students_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_pkey PRIMARY KEY (id);


--
-- Name: training_programs training_programs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_programs
    ADD CONSTRAINT training_programs_pkey PRIMARY KEY (id);


--
-- Name: training_programs training_programs_program_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_programs
    ADD CONSTRAINT training_programs_program_code_key UNIQUE (program_code);


--
-- Name: training_requirement_templates training_requirement_templates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_requirement_templates
    ADD CONSTRAINT training_requirement_templates_pkey PRIMARY KEY (id);


--
-- Name: training_requirements training_requirements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_requirements
    ADD CONSTRAINT training_requirements_pkey PRIMARY KEY (id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: enrollment_series_one_current; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX enrollment_series_one_current ON public.enrollment_series USING btree (is_current) WHERE is_current;


--
-- Name: idx_aircraft_maintenance_schedule_templates_model; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_aircraft_maintenance_schedule_templates_model ON public.aircraft_maintenance_schedule_templates USING btree (aircraft_model) WHERE is_active;


--
-- Name: idx_ba_tests_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ba_tests_date ON public.ba_tests USING btree (test_date);


--
-- Name: idx_daily_flying_reports_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_daily_flying_reports_date ON public.daily_flying_reports USING btree (report_date);


--
-- Name: idx_general_weather_cache_key; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_general_weather_cache_key ON public.general_weather_cache USING btree (cache_key);


--
-- Name: idx_holidays_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_holidays_date ON public.holidays USING btree (holiday_date);


--
-- Name: idx_maintenance_records_ticket_number; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_maintenance_records_ticket_number ON public.maintenance_records USING btree (ticket_number) WHERE (ticket_number IS NOT NULL);


--
-- Name: idx_notam_cache_key; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notam_cache_key ON public.notam_cache USING btree (cache_key);


--
-- Name: idx_safety_incidents_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_safety_incidents_date ON public.safety_incidents USING btree (incident_date);


--
-- Name: idx_safety_incidents_incident_number; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_safety_incidents_incident_number ON public.safety_incidents USING btree (incident_number) WHERE (incident_number IS NOT NULL);


--
-- Name: ground_school_classes ground_school_classes_subject_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ground_school_classes
    ADD CONSTRAINT ground_school_classes_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.ground_school_subjects(id);


--
-- Name: ground_school_enrollment ground_school_enrollment_class_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ground_school_enrollment
    ADD CONSTRAINT ground_school_enrollment_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.ground_school_classes(id);


--
-- Name: ground_school_enrollment ground_school_enrollment_student_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ground_school_enrollment
    ADD CONSTRAINT ground_school_enrollment_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- Name: instructor_roster_exceptions instructor_roster_exceptions_instructor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.instructor_roster_exceptions
    ADD CONSTRAINT instructor_roster_exceptions_instructor_id_fkey FOREIGN KEY (instructor_id) REFERENCES public.instructors(id) ON DELETE CASCADE;


--
-- Name: instructor_roster instructor_roster_instructor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.instructor_roster
    ADD CONSTRAINT instructor_roster_instructor_id_fkey FOREIGN KEY (instructor_id) REFERENCES public.instructors(id) ON DELETE CASCADE;


--
-- Name: password_reset_tokens password_reset_tokens_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: training_requirements training_requirements_student_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_requirements
    ADD CONSTRAINT training_requirements_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- Name: training_requirements training_requirements_template_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_requirements
    ADD CONSTRAINT training_requirements_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.training_requirement_templates(id) ON DELETE SET NULL;


--
-- Name: users users_student_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- Name: aircraft; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.aircraft ENABLE ROW LEVEL SECURITY;

--
-- Name: aircraft_maintenance_schedule_templates; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.aircraft_maintenance_schedule_templates ENABLE ROW LEVEL SECURITY;

--
-- Name: ames; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.ames ENABLE ROW LEVEL SECURITY;

--
-- Name: availability; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.availability ENABLE ROW LEVEL SECURITY;

--
-- Name: ba_tests; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.ba_tests ENABLE ROW LEVEL SECURITY;

--
-- Name: daily_flying_reports; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.daily_flying_reports ENABLE ROW LEVEL SECURITY;

--
-- Name: enrollment_series; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.enrollment_series ENABLE ROW LEVEL SECURITY;

--
-- Name: exercises; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.exercises ENABLE ROW LEVEL SECURITY;

--
-- Name: flight_records; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.flight_records ENABLE ROW LEVEL SECURITY;

--
-- Name: fto_settings; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.fto_settings ENABLE ROW LEVEL SECURITY;

--
-- Name: fuel_records; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.fuel_records ENABLE ROW LEVEL SECURITY;

--
-- Name: general_weather_cache; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.general_weather_cache ENABLE ROW LEVEL SECURITY;

--
-- Name: ground_school_classes; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.ground_school_classes ENABLE ROW LEVEL SECURITY;

--
-- Name: ground_school_enrollment; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.ground_school_enrollment ENABLE ROW LEVEL SECURITY;

--
-- Name: ground_school_subjects; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.ground_school_subjects ENABLE ROW LEVEL SECURITY;

--
-- Name: holidays; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.holidays ENABLE ROW LEVEL SECURITY;

--
-- Name: instructor_roles; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.instructor_roles ENABLE ROW LEVEL SECURITY;

--
-- Name: instructor_roster; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.instructor_roster ENABLE ROW LEVEL SECURITY;

--
-- Name: instructor_roster_exceptions; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.instructor_roster_exceptions ENABLE ROW LEVEL SECURITY;

--
-- Name: instructors; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.instructors ENABLE ROW LEVEL SECURITY;

--
-- Name: login_audit; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.login_audit ENABLE ROW LEVEL SECURITY;

--
-- Name: maintenance_records; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.maintenance_records ENABLE ROW LEVEL SECURITY;

--
-- Name: notam_cache; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.notam_cache ENABLE ROW LEVEL SECURITY;

--
-- Name: notification_log; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.notification_log ENABLE ROW LEVEL SECURITY;

--
-- Name: password_reset_tokens; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.password_reset_tokens ENABLE ROW LEVEL SECURITY;

--
-- Name: safety_incidents; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.safety_incidents ENABLE ROW LEVEL SECURITY;

--
-- Name: scheduled_flights; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.scheduled_flights ENABLE ROW LEVEL SECURITY;

--
-- Name: sortie_types; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.sortie_types ENABLE ROW LEVEL SECURITY;

--
-- Name: students; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;

--
-- Name: training_programs; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.training_programs ENABLE ROW LEVEL SECURITY;

--
-- Name: training_requirement_templates; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.training_requirement_templates ENABLE ROW LEVEL SECURITY;

--
-- Name: training_requirements; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.training_requirements ENABLE ROW LEVEL SECURITY;

--
-- Name: users; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict oeXTRM7DjqUY5cN2PA98Az2Cl4aLWzfPbOSONM19Myexjlr7MY52wlcciSZ9uXB

